language: go

go:
  - 1.9

env:
  - PATH=$PATH:$GOPATH/bin

install:
  # - go get -u github.com/mattn/go-colorable
  # - go get -u github.com/urfave/cli
  # - go get -u github.com/b4b4r07/tfnotify
  - go get -v github.com/golang/dep/cmd/dep
  - git clone https://github.com/b4b4r07/tfnotify
  - cd tfnotify
  - dep ensure
  - go install -v

before_script:
  - which tfnotify
  - tfnotify --help

script:
  echo "Plan\: 1 to add" | tfnotify plan
