language: go

go:
  - 1.9

install:
  # - go get -u github.com/mattn/go-colorable
  # - go get -u github.com/urfave/cli
  # - go get -u github.com/b4b4r07/tfnotify
  - go get -v github.com/golang/dep/cmd/dep
  - git clone https://github.com/b4b4r07/tfnotify
  - cd tfnotify
  - dep ensure
  - go install

before_script:
  - echo before

script:
  echo "Plan: 1 to add" | tfnotify plan
